name: Docker CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # Job 1: Constrói a imagem e faz o upload para o Docker Hub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Autenticação no Docker Hub usando as Secrets cadastradas
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build e Push da imagem com a sua conta no Docker Hub
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pudim-site:latest

  # Job 2: Baixa a imagem do Docker Hub e executa os testes dentro do container
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Rodar verificação dentro do Container
        run: docker run ${{ secrets.DOCKER_USER }}/pudim-site:latest nginx -t